# Kernel SVM

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('my_project.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

## Filling up the missing values

In [3]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 0:4])
X[:, 0:4] = imputer.transform(X[:, 0:4])

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[23.  3.  1.  2.]
 [79.  4.  4.  5.]
 [22.  1.  1.  2.]
 ...
 [31.  2.  1.  2.]
 [83.  4.  5.  6.]
 [64.  4.  3.  4.]]


In [6]:
print(y_train)

[0 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 1 0
 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 1
 0 0 1 0 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 1 0 0
 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 1 1
 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1
 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 1 0 1
 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1
 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0
 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1
 0 0 0 1 1 0 1 1 1 1 1 1 

In [7]:
print(X_test)

[[43.  3.  4.  5.]
 [45.  1.  1.  2.]
 [60.  2.  1.  2.]
 [23.  2.  1.  2.]
 [55.  2.  1.  2.]
 [67.  4.  4.  5.]
 [56.  1.  1.  2.]
 [71.  2.  4.  5.]
 [50.  2.  1.  2.]
 [67.  4.  1.  2.]
 [54.  4.  4.  5.]
 [57.  1.  1.  2.]
 [80.  4.  5.  6.]
 [49.  2.  1.  2.]
 [76.  4.  3.  4.]
 [67.  4.  2.  3.]
 [60.  4.  3.  4.]
 [50.  4.  5.  6.]
 [71.  4.  4.  5.]
 [36.  1.  1.  2.]
 [61.  3.  4.  5.]
 [62.  3.  3.  4.]
 [42.  1.  1.  2.]
 [52.  4.  4.  5.]
 [43.  1.  1.  2.]
 [56.  4.  4.  5.]
 [46.  1.  1.  2.]
 [52.  3.  5.  6.]
 [71.  4.  2.  3.]
 [60.  4.  3.  4.]
 [46.  4.  4.  5.]
 [35.  1.  1.  2.]
 [67.  4.  4.  5.]
 [55.  3.  3.  4.]
 [71.  4.  5.  6.]
 [46.  4.  4.  5.]
 [47.  2.  1.  2.]
 [71.  4.  4.  5.]
 [46.  4.  5.  6.]
 [35.  1.  1.  2.]
 [48.  1.  1.  2.]
 [60.  4.  4.  5.]
 [53.  2.  1.  2.]
 [46.  3.  5.  6.]
 [40.  4.  1.  2.]
 [57.  2.  1.  2.]
 [56.  2.  4.  5.]
 [72.  4.  4.  5.]
 [67.  1.  1.  2.]
 [65.  3.  4.  5.]
 [62.  3.  3.  4.]
 [71.  1.  1.  2.]
 [65.  2.  1

In [8]:
print(y_test)

[0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0
 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0
 1 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1
 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1
 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1
 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 0]


## Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[-2.23682726  0.19442378 -1.21977335 -1.21977335]
 [ 1.6149291   1.01305024  0.75379252  0.75379252]
 [-2.30560863 -1.44282913 -1.21977335 -1.21977335]
 ...
 [-1.68657635 -0.62420267 -1.21977335 -1.21977335]
 [ 1.89005456  1.01305024  1.41164781  1.41164781]
 [ 0.58320865  1.01305024  0.09593723  0.09593723]]


In [11]:
print(X_test)

[[-0.86119999  0.19442378  0.75379252  0.75379252]
 [-0.72363726 -1.44282913 -1.21977335 -1.21977335]
 [ 0.30808319 -0.62420267 -1.21977335 -1.21977335]
 [-2.23682726 -0.62420267 -1.21977335 -1.21977335]
 [-0.03582363 -0.62420267 -1.21977335 -1.21977335]
 [ 0.78955274  1.01305024  0.75379252  0.75379252]
 [ 0.03295774 -1.44282913 -1.21977335 -1.21977335]
 [ 1.06467819 -0.62420267  0.75379252  0.75379252]
 [-0.37973045 -0.62420267 -1.21977335 -1.21977335]
 [ 0.78955274  1.01305024 -1.21977335 -1.21977335]
 [-0.10460499  1.01305024  0.75379252  0.75379252]
 [ 0.1017391  -1.44282913 -1.21977335 -1.21977335]
 [ 1.68371046  1.01305024  1.41164781  1.41164781]
 [-0.44851181 -0.62420267 -1.21977335 -1.21977335]
 [ 1.40858501  1.01305024  0.09593723  0.09593723]
 [ 0.78955274  1.01305024 -0.56191806 -0.56191806]
 [ 0.30808319  1.01305024  0.09593723  0.09593723]
 [-0.37973045  1.01305024  1.41164781  1.41164781]
 [ 1.06467819  1.01305024  0.75379252  0.75379252]
 [-1.34266954 -1.44282913 -1.21

## Training the Kernel SVM model on the Training set

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting a new result

In [13]:
print(classifier.predict(sc.transform([[57,1,5,6]])))

[1]


## Predicting the Test set results

In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]

## Making the Confusion Matrix

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[104  25]
 [ 26  86]]


0.7883817427385892

## Applying k-Fold Cross Validation

In [16]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 81.25 %
Standard Deviation: 2.99 %
