# K-Nearest Neighbors (K-NN) Model

## Importing the libraries

In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [51]:
dataset = pd.read_csv('my_project.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [52]:
print(X)

[[67.  3.  5.  6.]
 [43.  1.  1.  2.]
 [58.  4.  5.  6.]
 ...
 [64.  4.  5.  6.]
 [66.  4.  5.  6.]
 [62.  3.  3.  4.]]


## Filling up the missing values


In [53]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 0:4])
X[:, 0:4] = imputer.transform(X[:, 0:4])

## Splitting the dataset into the Training set and Test set Filling up the missing values

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [55]:
print(X_train)

[[32.  2.  1.  2.]
 [49.  4.  4.  5.]
 [57.  2.  5.  6.]
 ...
 [31.  2.  1.  2.]
 [83.  4.  5.  6.]
 [64.  4.  3.  4.]]


In [56]:
print(y_train)

[0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1
 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1
 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 0 0 1
 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1
 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1
 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0
 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1
 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1
 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0
 1 1 0 0 1 1 0 0 0 1 0 1 

In [57]:
print(X_test)

[[43.  3.  4.  5.]
 [45.  1.  1.  2.]
 [60.  2.  1.  2.]
 [23.  2.  1.  2.]
 [55.  2.  1.  2.]
 [67.  4.  4.  5.]
 [56.  1.  1.  2.]
 [71.  2.  4.  5.]
 [50.  2.  1.  2.]
 [67.  4.  1.  2.]
 [54.  4.  4.  5.]
 [57.  1.  1.  2.]
 [80.  4.  5.  6.]
 [49.  2.  1.  2.]
 [76.  4.  3.  4.]
 [67.  4.  2.  3.]
 [60.  4.  3.  4.]
 [50.  4.  5.  6.]
 [71.  4.  4.  5.]
 [36.  1.  1.  2.]
 [61.  3.  4.  5.]
 [62.  3.  3.  4.]
 [42.  1.  1.  2.]
 [52.  4.  4.  5.]
 [43.  1.  1.  2.]
 [56.  4.  4.  5.]
 [46.  1.  1.  2.]
 [52.  3.  5.  6.]
 [71.  4.  2.  3.]
 [60.  4.  3.  4.]
 [46.  4.  4.  5.]
 [35.  1.  1.  2.]
 [67.  4.  4.  5.]
 [55.  3.  3.  4.]
 [71.  4.  5.  6.]
 [46.  4.  4.  5.]
 [47.  2.  1.  2.]
 [71.  4.  4.  5.]
 [46.  4.  5.  6.]
 [35.  1.  1.  2.]
 [48.  1.  1.  2.]
 [60.  4.  4.  5.]
 [53.  2.  1.  2.]
 [46.  3.  5.  6.]
 [40.  4.  1.  2.]
 [57.  2.  1.  2.]
 [56.  2.  4.  5.]
 [72.  4.  4.  5.]
 [67.  1.  1.  2.]
 [65.  3.  4.  5.]
 [62.  3.  3.  4.]
 [71.  1.  1.  2.]
 [65.  2.  1

In [58]:
print(y_test)

[0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0
 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0
 1 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1
 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1
 1 1 0 1 1 1 1 1]


## Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
print(X_train)

[[-1.59185384 -0.60203637 -1.19034395 -1.19034395]
 [-0.42974001  1.03175844  0.7770538   0.7770538 ]
 [ 0.11713709 -0.60203637  1.43285304  1.43285304]
 ...
 [-1.66021347 -0.60203637 -1.19034395 -1.19034395]
 [ 1.89448764  1.03175844  1.43285304  1.43285304]
 [ 0.59565454  1.03175844  0.12125455  0.12125455]]


In [61]:
print(X_test)

[[-0.83989783  0.21486104  0.7770538   0.7770538 ]
 [-0.70317856 -1.41893377 -1.19034395 -1.19034395]
 [ 0.322216   -0.60203637 -1.19034395 -1.19034395]
 [-2.20709057 -0.60203637 -1.19034395 -1.19034395]
 [-0.01958219 -0.60203637 -1.19034395 -1.19034395]
 [ 0.80073345  1.03175844  0.7770538   0.7770538 ]
 [ 0.04877745 -1.41893377 -1.19034395 -1.19034395]
 [ 1.074172   -0.60203637  0.7770538   0.7770538 ]
 [-0.36138037 -0.60203637 -1.19034395 -1.19034395]
 [ 0.80073345  1.03175844 -1.19034395 -1.19034395]
 [-0.08794182  1.03175844  0.7770538   0.7770538 ]
 [ 0.11713709 -1.41893377 -1.19034395 -1.19034395]
 [ 1.68940873  1.03175844  1.43285304  1.43285304]
 [-0.42974001 -0.60203637 -1.19034395 -1.19034395]
 [ 1.41597019  1.03175844  0.12125455  0.12125455]
 [ 0.80073345  1.03175844 -0.5345447  -0.5345447 ]
 [ 0.322216    1.03175844  0.12125455  0.12125455]
 [-0.36138037  1.03175844  1.43285304  1.43285304]
 [ 1.074172    1.03175844  0.7770538   0.7770538 ]
 [-1.31841529 -1.41893377 -1.19

## Training the K-NN model on the Training set

In [62]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predicting a new result

In [63]:
print(classifier.predict(sc.transform([[57,1,5,6]])))

[1]


## Predicting the Test set results

In [64]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]

## Making the Confusion Matrix

In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[84 16]
 [21 72]]


0.8082901554404145


## Applying k-Fold Cross Validation

In [66]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 78.78 %
Standard Deviation: 4.74 %
