# Logistic Regression

## Importing the libraries

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [15]:
 dataset = pd.read_csv('my_project.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

## Filling up the missing values

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 0:4])
X[:, 0:4] = imputer.transform(X[:, 0:4])

## Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
print(X_train)

[[32.  2.  1.  2.]
 [49.  4.  4.  5.]
 [57.  2.  5.  6.]
 ...
 [31.  2.  1.  2.]
 [83.  4.  5.  6.]
 [64.  4.  3.  4.]]


In [19]:
print(y_train)

[0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 1
 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1
 0 1 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1
 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 0 1 0 1 0 0 1
 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1
 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1
 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0
 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1
 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1
 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 0 0
 1 1 0 0 1 1 0 0 0 1 0 1 

In [20]:
print(X_test)

[[43.  3.  4.  5.]
 [45.  1.  1.  2.]
 [60.  2.  1.  2.]
 [23.  2.  1.  2.]
 [55.  2.  1.  2.]
 [67.  4.  4.  5.]
 [56.  1.  1.  2.]
 [71.  2.  4.  5.]
 [50.  2.  1.  2.]
 [67.  4.  1.  2.]
 [54.  4.  4.  5.]
 [57.  1.  1.  2.]
 [80.  4.  5.  6.]
 [49.  2.  1.  2.]
 [76.  4.  3.  4.]
 [67.  4.  2.  3.]
 [60.  4.  3.  4.]
 [50.  4.  5.  6.]
 [71.  4.  4.  5.]
 [36.  1.  1.  2.]
 [61.  3.  4.  5.]
 [62.  3.  3.  4.]
 [42.  1.  1.  2.]
 [52.  4.  4.  5.]
 [43.  1.  1.  2.]
 [56.  4.  4.  5.]
 [46.  1.  1.  2.]
 [52.  3.  5.  6.]
 [71.  4.  2.  3.]
 [60.  4.  3.  4.]
 [46.  4.  4.  5.]
 [35.  1.  1.  2.]
 [67.  4.  4.  5.]
 [55.  3.  3.  4.]
 [71.  4.  5.  6.]
 [46.  4.  4.  5.]
 [47.  2.  1.  2.]
 [71.  4.  4.  5.]
 [46.  4.  5.  6.]
 [35.  1.  1.  2.]
 [48.  1.  1.  2.]
 [60.  4.  4.  5.]
 [53.  2.  1.  2.]
 [46.  3.  5.  6.]
 [40.  4.  1.  2.]
 [57.  2.  1.  2.]
 [56.  2.  4.  5.]
 [72.  4.  4.  5.]
 [67.  1.  1.  2.]
 [65.  3.  4.  5.]
 [62.  3.  3.  4.]
 [71.  1.  1.  2.]
 [65.  2.  1

In [21]:
print(y_test)

[0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0
 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0 0
 0 0 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0
 1 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 1
 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1
 1 1 0 1 1 1 1 1]


## Feature Scaling

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
print(X_train)

[[-1.59185384 -0.60203637 -1.19034395 -1.19034395]
 [-0.42974001  1.03175844  0.7770538   0.7770538 ]
 [ 0.11713709 -0.60203637  1.43285304  1.43285304]
 ...
 [-1.66021347 -0.60203637 -1.19034395 -1.19034395]
 [ 1.89448764  1.03175844  1.43285304  1.43285304]
 [ 0.59565454  1.03175844  0.12125455  0.12125455]]


In [24]:
print(X_test)

[[-0.83989783  0.21486104  0.7770538   0.7770538 ]
 [-0.70317856 -1.41893377 -1.19034395 -1.19034395]
 [ 0.322216   -0.60203637 -1.19034395 -1.19034395]
 [-2.20709057 -0.60203637 -1.19034395 -1.19034395]
 [-0.01958219 -0.60203637 -1.19034395 -1.19034395]
 [ 0.80073345  1.03175844  0.7770538   0.7770538 ]
 [ 0.04877745 -1.41893377 -1.19034395 -1.19034395]
 [ 1.074172   -0.60203637  0.7770538   0.7770538 ]
 [-0.36138037 -0.60203637 -1.19034395 -1.19034395]
 [ 0.80073345  1.03175844 -1.19034395 -1.19034395]
 [-0.08794182  1.03175844  0.7770538   0.7770538 ]
 [ 0.11713709 -1.41893377 -1.19034395 -1.19034395]
 [ 1.68940873  1.03175844  1.43285304  1.43285304]
 [-0.42974001 -0.60203637 -1.19034395 -1.19034395]
 [ 1.41597019  1.03175844  0.12125455  0.12125455]
 [ 0.80073345  1.03175844 -0.5345447  -0.5345447 ]
 [ 0.322216    1.03175844  0.12125455  0.12125455]
 [-0.36138037  1.03175844  1.43285304  1.43285304]
 [ 1.074172    1.03175844  0.7770538   0.7770538 ]
 [-1.31841529 -1.41893377 -1.19

## Training the Logistic Regression model on the Training set

In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [26]:
print(classifier.predict(sc.transform([[ 57,1,5,6]])))

[0]


## Predicting the Test set results

In [27]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]

## Making the Confusion Matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[81 19]
 [20 73]]


0.7979274611398963

## Applying k-Fold Cross Validation

In [29]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 79.30 %
Standard Deviation: 5.07 %
